---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.22.1-bullseye

inputs:
  - name: dp-legacy-redirector

outputs:
  - name: build

run:
  path: dp-legacy-redirector/ci/scripts/build.sh
